# -*- coding: utf-8 -*-
from pathlib import Path

d = "div"
p = Path(__file__).resolve().parent.parent / "index.html"
text = p.read_text(encoding="utf-8")

idx_app = text.find('  <div id="app"')
idx_level = text.find(f'  <{d} id="level-picker"')
if idx_app < 0 or idx_level < 0:
    raise SystemExit("markers not found")

parts = []
parts.append(f'  <{d} id="app" class="app-shell">')
parts.append(f'    <{d} class="app-main">')
parts.append("      <header class=\"header\">")
parts.append("        <h1 class=\"title\">豆豆大挑战</h1>")
parts.append(f'        <{d} id="combo-hud" class="combo-hud hidden">连击 x0</{d}>')
parts.append(f'        <{d} class="stats">')
parts.append('          <span id="level-label">第 1 关</span>')
parts.append('          <span id="moves-label">步数: 0</span>')
parts.append('          <span id="timer-label">时间: 0s</span>')
parts.append(f"        </{d}>")
parts.append(f'        <{d} class="header-actions">')
parts.append('          <button id="btn-hint" type="button" class="btn-hint hidden" title="提示">💡<span id="hint-count"></span></button>')
parts.append('          <button id="btn-sound" type="button" class="btn-sound" aria-label="音效开关" title="音效">🔊</button>')
parts.append('          <button id="btn-menu" type="button" class="btn-menu hidden">菜单</button>')
parts.append(f"        </{d}>")
parts.append("      </header>")
parts.append("")
parts.append('      <section id="home-main" class="home-main" aria-label="欢迎">')
parts.append('        <p class="home-main-tagline">表情包记忆配对</p>')
parts.append('        <p id="home-main-status" class="home-main-status"></p>')
parts.append('        <p id="home-hint" class="home-hint">选关或快速开始 · 每局随机表情包</p>')
parts.append(f'        <{d} class="home-main-actions">')
parts.append('          <button type="button" id="btn-quick-start" class="home-main-btn home-main-btn--primary">快速开始</button>')
parts.append('          <button type="button" id="btn-open-menu" class="home-main-btn">游戏菜单</button>')
parts.append(f"        </{d}>")
parts.append("      </section>")
parts.append("")
parts.append('      <section id="sub-panel" class="sub-panel hidden" aria-hidden="true">')
parts.append(f'        <{d} class="sub-panel-head">')
parts.append('          <h2 id="sub-panel-title"></h2>')
parts.append('          <button type="button" id="btn-sub-back" class="toolbar-btn">返回</button>')
parts.append(f"        </{d}>")
parts.append(f'        <{d} id="sub-panel-body" class="sub-panel-body"></{d}>')
parts.append("      </section>")
parts.append("")
parts.append(f'      <{d} id="board-viewport" class="board-viewport hidden" aria-hidden="true">')
parts.append(f'        <{d} id="board-scaler" class="board-scaler">')
parts.append('          <main id="board" class="board" aria-label="游戏棋盘"></main>')
parts.append(f"        </{d}>")
parts.append(f"      </{d}>")
parts.append("")
parts.append(f'      <p id="error-msg" class="error-msg hidden"></p>')
parts.append(f"    </{d}>")
parts.append(f"  </{d}>")
parts.append("")
parts.append(f'  <{d} id="menu-modal" class="menu-modal hidden" aria-hidden="true">')
parts.append(f'    <{d} class="menu-modal-sheet" role="dialog" aria-labelledby="menu-modal-title">')
parts.append(f'      <{d} class="menu-modal-head">')
parts.append('        <h2 id="menu-modal-title">游戏菜单</h2>')
parts.append('        <button type="button" id="btn-menu-close" class="menu-modal-close" aria-label="关闭">×</button>')
parts.append(f"      </{d}>")
parts.append(f'      <{d} id="home-hub" class="menu-modal-body">')
parts.append(f'        <{d} class="mode-select" role="group" aria-label="游戏模式">')
parts.append('          <p class="mode-select-title">游戏模式</p>')
parts.append(f'          <{d} id="mode-list" class="mode-list"></{d}>')
parts.append(f"        </{d}>")
parts.append(f'        <{d} id="daily-card" class="daily-card hidden"></{d}>')
parts.append(f'        <{d} class="home-actions">')
parts.append('          <button type="button" id="btn-pick-level" class="home-btn home-btn--primary">选关</button>')
parts.append(f"        </{d}>")
parts.append(f'        <{d} class="home-toolbar">')
parts.append('          <button type="button" id="btn-achievements" class="toolbar-btn">成就</button>')
parts.append('          <button type="button" id="btn-gallery" class="toolbar-btn">图鉴</button>')
parts.append(f"        </{d}>")
parts.append(f"      </{d}>")
parts.append(f"    </{d}>")
parts.append(f"  </{d}>")
parts.append("")
parts.append("")

new_block = "\n".join(parts)
text = text[:idx_app] + new_block + text[idx_level:]
p.write_text(text, encoding="utf-8")
print("patched index.html")
